#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run check-types || (echo 'check-types failed.' && return false;)

npm run check-lint || (echo 'check-lint failed.' && return false;)

npm run check-format || (echo 'check-format failed.' && return false;)

npm run compile || (echo 'build failed.' && return false;)

echo 'pre-commit checks passed!'